### ISSUE TITLE
Als Spieler möchte ich Hintergrundmusik haben und die Möglichkeit haben diese ein/ausschalten zu können

### ISSUE THREAD

**Issue by gitolafson** [gitolafson/Tankinator#11]

**Comment by allenab** [comment]
-> Hintergrundmusik funktioniert
-> Beim wechseln der verschiedenen Views ändert sich auch die Hintergrundmusik
x ein eventuelle Setting View zum generellen ein/ausschalten könnte noch bei bedarf hinzugefügt werden
